name: "Continuous Integration"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  continuous-integration:
    name: continuous-integration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16, 18, 20, 22, 23, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
      - name: install dependencies
        run: |
          npm ci
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm test